// kamoji.h - Geedo kaomoji face pack (auto-generated by tools/kaomoji_gen.py)
// Do not hand-edit; add faces/glyphs in the generator and re-run.
//
// kaomoji_render() draws into a 1024-byte SSD1306 page buffer - the same
// frame format as the GDA1 animation container - so the result can go
// through the exact display path the animation player already uses.
#pragma once
#include <stdint.h>
#include <string.h>
#if defined(ARDUINO)
#include <pgmspace.h>
#else
#define PROGMEM
#define pgm_read_byte(p)  (*(const uint8_t*)(p))
#define pgm_read_word(p)  (*(const uint16_t*)(p))
#define pgm_read_ptr(p)   (*(const void* const*)(p))
#endif

#define KAOMOJI_COUNT 191
#define KAOMOJI_GLYPHS 103
#define KAOMOJI_CELL_H 14
#define KAOMOJI_TOP 25

// each glyph: [width][14 x uint16 row bitmaps, MSB-first]
static const uint16_t KG_0[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // ' ' w=4
static const uint16_t KG_1[14] PROGMEM = {0x1800,0x2000,0x4000,0x4000,0x8000,0x8000,0x8000,0x8000,0x8000,0x4000,0x4000,0x2000,0x1800,0x0000}; // '(' w=5
static const uint16_t KG_2[14] PROGMEM = {0xc000,0x2000,0x1000,0x1000,0x0800,0x0800,0x0800,0x0800,0x0800,0x1000,0x1000,0x2000,0xc000,0x0000}; // ')' w=5
static const uint16_t KG_3[14] PROGMEM = {0xf000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0xf000,0x0000}; // '[' w=4
static const uint16_t KG_4[14] PROGMEM = {0xf000,0x1000,0x1000,0x1000,0x1000,0x1000,0x1000,0x1000,0x1000,0x1000,0x1000,0x1000,0xf000,0x0000}; // ']' w=4
static const uint16_t KG_5[14] PROGMEM = {0x0100,0x0200,0x0200,0x0400,0x0400,0x0800,0x0800,0x1000,0x1000,0x2000,0x2000,0x4000,0x4000,0x8000}; // '/' w=8
static const uint16_t KG_6[14] PROGMEM = {0x8000,0x4000,0x4000,0x2000,0x2000,0x1000,0x1000,0x0800,0x0800,0x0400,0x0400,0x0200,0x0200,0x0100}; // '\\' w=8
static const uint16_t KG_7[14] PROGMEM = {0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x0000}; // '|' w=1
static const uint16_t KG_8[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xff00,0x0000}; // '_' w=8
static const uint16_t KG_9[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xfc00,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '-' w=6
static const uint16_t KG_10[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0x6100,0x9200,0x8c00,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '~' w=8
static const uint16_t KG_11[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x7e00,0x0000,0x7e00,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '=' w=7
static const uint16_t KG_12[14] PROGMEM = {0x0000,0x0000,0x0000,0x1000,0x1000,0x1000,0xfe00,0x1000,0x1000,0x1000,0x0000,0x0000,0x0000,0x0000}; // '+' w=7
static const uint16_t KG_13[14] PROGMEM = {0x0000,0x0000,0x2400,0x1800,0x7e00,0x1800,0x2400,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '*' w=8
static const uint16_t KG_14[14] PROGMEM = {0x0000,0x0000,0x1000,0x2800,0x4400,0x8200,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '^' w=7
static const uint16_t KG_15[14] PROGMEM = {0x0000,0x0000,0x0400,0x0800,0x1000,0x2000,0x4000,0x8000,0x4000,0x2000,0x1000,0x0800,0x0400,0x0000}; // '<' w=6
static const uint16_t KG_16[14] PROGMEM = {0x0000,0x0000,0x8000,0x4000,0x2000,0x1000,0x0800,0x0400,0x0800,0x1000,0x2000,0x4000,0x8000,0x0000}; // '>' w=6
static const uint16_t KG_17[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x6000,0x6000,0x0000}; // '.' w=4
static const uint16_t KG_18[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x3000,0x3000,0x2000,0x4000}; // ',' w=4
static const uint16_t KG_19[14] PROGMEM = {0x0000,0x0000,0x0000,0x3000,0x3000,0x0000,0x0000,0x0000,0x0000,0x0000,0x3000,0x3000,0x2000,0x4000}; // ';' w=4
static const uint16_t KG_20[14] PROGMEM = {0x0000,0x0000,0x0000,0x6000,0x6000,0x0000,0x0000,0x0000,0x0000,0x0000,0x6000,0x6000,0x0000,0x0000}; // ':' w=4
static const uint16_t KG_21[14] PROGMEM = {0x6000,0x6000,0x4000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // "'" w=3
static const uint16_t KG_22[14] PROGMEM = {0xd800,0xd800,0x9000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '"' w=5
static const uint16_t KG_23[14] PROGMEM = {0x6000,0x6000,0x6000,0x6000,0x6000,0x6000,0x6000,0x6000,0x0000,0x0000,0x6000,0x6000,0x0000,0x0000}; // '!' w=4
static const uint16_t KG_24[14] PROGMEM = {0x7800,0x8400,0x8400,0x0400,0x0800,0x1000,0x2000,0x2000,0x0000,0x0000,0x2000,0x2000,0x0000,0x0000}; // '?' w=6
static const uint16_t KG_25[14] PROGMEM = {0x0000,0x2400,0x2400,0xff00,0x2400,0x2400,0x2400,0xff00,0x2400,0x2400,0x0000,0x0000,0x0000,0x0000}; // '#' w=8
static const uint16_t KG_26[14] PROGMEM = {0x7c00,0x8200,0x9a00,0xa600,0xa600,0xae00,0x9400,0x8000,0x7c00,0x0000,0x0000,0x0000,0x0000,0x0000}; // '@' w=7
static const uint16_t KG_27[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x7800,0x8400,0x8400,0x8400,0x8400,0x7800,0x0000,0x0000,0x0000,0x0000}; // 'o' w=6
static const uint16_t KG_28[14] PROGMEM = {0x0000,0x0000,0x7c00,0x8200,0x8200,0x8200,0x8200,0x8200,0x8200,0x7c00,0x0000,0x0000,0x0000,0x0000}; // 'O' w=7
static const uint16_t KG_29[14] PROGMEM = {0x0000,0x0000,0x7c00,0x8200,0x8600,0x8a00,0x9200,0xc200,0x8200,0x7c00,0x0000,0x0000,0x0000,0x0000}; // '0' w=7
static const uint16_t KG_30[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x8400,0x4800,0x3000,0x3000,0x4800,0x8400,0x0000,0x0000,0x0000,0x0000}; // 'x' w=6
static const uint16_t KG_31[14] PROGMEM = {0x0000,0x0000,0x8200,0x4400,0x2800,0x1000,0x1000,0x2800,0x4400,0x8200,0x0000,0x0000,0x0000,0x0000}; // 'X' w=7
static const uint16_t KG_32[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x8400,0x8400,0x8400,0x8400,0x8c00,0x7400,0x0000,0x0000,0x0000,0x0000}; // 'u' w=6
static const uint16_t KG_33[14] PROGMEM = {0x0000,0x0000,0x8200,0x8200,0x8200,0x8200,0x8200,0x8200,0x8200,0x7c00,0x0000,0x0000,0x0000,0x0000}; // 'U' w=7
static const uint16_t KG_34[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x8200,0x8200,0x4400,0x4400,0x2800,0x1000,0x0000,0x0000,0x0000,0x0000}; // 'v' w=7
static const uint16_t KG_35[14] PROGMEM = {0x0000,0x0000,0x8200,0x8200,0x8200,0x4400,0x4400,0x2800,0x2800,0x1000,0x0000,0x0000,0x0000,0x0000}; // 'V' w=7
static const uint16_t KG_36[14] PROGMEM = {0x0000,0x0000,0xfe00,0x1000,0x1000,0x1000,0x1000,0x1000,0x1000,0x1000,0x0000,0x0000,0x0000,0x0000}; // 'T' w=7
static const uint16_t KG_37[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x7800,0x8400,0x8000,0x8000,0x8400,0x7800,0x0000,0x0000,0x0000,0x0000}; // 'c' w=6
static const uint16_t KG_38[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0xfc00,0x0800,0x1000,0x2000,0x4000,0xfc00,0x0000,0x0000,0x0000,0x0000}; // 'z' w=6
static const uint16_t KG_39[14] PROGMEM = {0x0000,0x0000,0xfe00,0x0400,0x0800,0x1000,0x2000,0x4000,0x8000,0xfe00,0x0000,0x0000,0x0000,0x0000}; // 'Z' w=7
static const uint16_t KG_40[14] PROGMEM = {0x0000,0x0000,0x9200,0x9200,0x9200,0x9200,0x9200,0x9200,0xba00,0x4400,0x0000,0x0000,0x0000,0x0000}; // 'W' w=7
static const uint16_t KG_41[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x9200,0x9200,0x9200,0x9200,0xba00,0x4400,0x0000,0x0000,0x0000,0x0000}; // 'w' w=7
static const uint16_t KG_42[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0xb800,0xc400,0x8400,0x8400,0x8400,0x8400,0x0000,0x0000,0x0000,0x0000}; // 'n' w=6
static const uint16_t KG_43[14] PROGMEM = {0x0000,0x0400,0x0400,0x0400,0x7c00,0x8400,0x8400,0x8400,0x8400,0x7c00,0x0000,0x0000,0x0000,0x0000}; // 'd' w=6
static const uint16_t KG_44[14] PROGMEM = {0x0000,0x8000,0x8000,0x8000,0xf800,0x8400,0x8400,0x8400,0x8400,0xf800,0x0000,0x0000,0x0000,0x0000}; // 'b' w=6
static const uint16_t KG_45[14] PROGMEM = {0x0000,0x0000,0x7800,0x8400,0x0400,0x3800,0x0400,0x0400,0x8400,0x7800,0x0000,0x0000,0x0000,0x0000}; // '3' w=6
static const uint16_t KG_46[14] PROGMEM = {0x0000,0x0000,0x7800,0x8400,0x8400,0x7c00,0x0400,0x0400,0x8400,0x7800,0x0000,0x0000,0x0000,0x0000}; // '9' w=6
static const uint16_t KG_47[14] PROGMEM = {0x1800,0x3000,0x6000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '´' w=5
static const uint16_t KG_48[14] PROGMEM = {0xc000,0x6000,0x3000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '`' w=5
static const uint16_t KG_49[14] PROGMEM = {0x8400,0x8400,0x7800,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '˘' w=6
static const uint16_t KG_50[14] PROGMEM = {0xfc00,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '¯' w=6
static const uint16_t KG_51[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0xfc00,0x0400,0x0400,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '¬' w=6
static const uint16_t KG_52[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0xfc00,0x8000,0x8000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '⌐' w=6
static const uint16_t KG_53[14] PROGMEM = {0x6000,0x9000,0x9000,0x6000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '°' w=4
static const uint16_t KG_54[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0x6000,0xf000,0x6000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '・' w=4
static const uint16_t KG_55[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x7000,0xf800,0xf800,0x7000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '•' w=5
static const uint16_t KG_56[14] PROGMEM = {0x0000,0x7c00,0x8200,0xb200,0xca00,0xca00,0xb200,0x8200,0xfe00,0x7c00,0x0000,0x0000,0x0000,0x0000}; // '◕' w=7
static const uint16_t KG_57[14] PROGMEM = {0x0000,0x7c00,0xfe00,0xfe00,0xfe00,0xfe00,0xfe00,0xfe00,0xfe00,0x7c00,0x0000,0x0000,0x0000,0x0000}; // '●' w=7
static const uint16_t KG_58[14] PROGMEM = {0x0000,0x7c00,0x8200,0x8200,0x8200,0x8200,0x8200,0x8200,0x8200,0x7c00,0x0000,0x0000,0x0000,0x0000}; // '○' w=7
static const uint16_t KG_59[14] PROGMEM = {0x0000,0x7c00,0x8200,0x8200,0x9200,0xba00,0x9200,0x8200,0x8200,0x7c00,0x0000,0x0000,0x0000,0x0000}; // '⊙' w=7
static const uint16_t KG_60[14] PROGMEM = {0x0000,0xff00,0x8100,0x8100,0x8100,0x8100,0x8100,0x8100,0x8100,0xff00,0x0000,0x0000,0x0000,0x0000}; // '□' w=8
static const uint16_t KG_61[14] PROGMEM = {0x0000,0xff00,0xff00,0xff00,0xff00,0xff00,0xff00,0xff00,0xff00,0xff00,0x0000,0x0000,0x0000,0x0000}; // '■' w=8
static const uint16_t KG_62[14] PROGMEM = {0x0000,0xff80,0x4100,0x4100,0x2200,0x2200,0x1400,0x1400,0x0800,0x0000,0x0000,0x0000,0x0000,0x0000}; // '▽' w=9
static const uint16_t KG_63[14] PROGMEM = {0x0800,0x0800,0x1c00,0xff80,0x7f00,0x3e00,0x2200,0x4100,0x8080,0x0000,0x0000,0x0000,0x0000,0x0000}; // '☆' w=9
static const uint16_t KG_64[14] PROGMEM = {0x0800,0x0800,0x1c00,0xff80,0x7f00,0x3e00,0x3e00,0x6300,0xc180,0x0000,0x0000,0x0000,0x0000,0x0000}; // '★' w=9
static const uint16_t KG_65[14] PROGMEM = {0x0000,0x6600,0x9900,0x8100,0x8100,0x4200,0x2400,0x1800,0x0800,0x0000,0x0000,0x0000,0x0000,0x0000}; // '♡' w=8
static const uint16_t KG_66[14] PROGMEM = {0x0000,0x6600,0xff00,0xff00,0xff00,0x7e00,0x3c00,0x1800,0x0800,0x0000,0x0000,0x0000,0x0000,0x0000}; // '♥' w=8
static const uint16_t KG_67[14] PROGMEM = {0x0800,0x0c00,0x0a00,0x0900,0x0800,0x0800,0x0800,0x3800,0x7800,0x3000,0x0000,0x0000,0x0000,0x0000}; // '♪' w=8
static const uint16_t KG_68[14] PROGMEM = {0x0000,0x0000,0x3c00,0x4200,0x8100,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '⌒' w=8
static const uint16_t KG_69[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x8100,0x4200,0x3c00,0x0000,0x0000}; // '‿' w=8
static const uint16_t KG_70[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x9900,0x9900,0x9900,0x9900,0x9900,0x6600,0x0000,0x0000,0x0000,0x0000}; // 'ω' w=8
static const uint16_t KG_71[14] PROGMEM = {0x0000,0x0000,0x0000,0x7800,0x8000,0x8000,0x7000,0x8000,0x8000,0x7800,0x0000,0x0000,0x0000,0x0000}; // 'ε' w=5
static const uint16_t KG_72[14] PROGMEM = {0x0000,0x0000,0x7e00,0x2200,0x2200,0x2200,0x2200,0x2200,0x4200,0xff00,0x8100,0x8100,0x0000,0x0000}; // 'Д' w=8
static const uint16_t KG_73[14] PROGMEM = {0x0000,0xfe00,0x4000,0x2000,0x1000,0x0800,0x1000,0x2000,0x4000,0xfe00,0x0000,0x0000,0x0000,0x0000}; // 'Σ' w=7
static const uint16_t KG_74[14] PROGMEM = {0x0000,0xa100,0x5100,0x1200,0x0200,0x0400,0x0400,0x0800,0x1000,0x6000,0x0000,0x0000,0x0000,0x0000}; // 'ツ' w=8
static const uint16_t KG_75[14] PROGMEM = {0x0000,0x0000,0xff00,0x0100,0x0100,0x0100,0x0200,0x0400,0x0800,0x3000,0x0000,0x0000,0x0000,0x0000}; // 'ヮ' w=8
static const uint16_t KG_76[14] PROGMEM = {0x0000,0x0100,0x0100,0x0200,0x0200,0x0400,0x0800,0x1000,0x2000,0xc000,0x0000,0x0000,0x0000,0x0000}; // 'ノ' w=8
static const uint16_t KG_77[14] PROGMEM = {0x0000,0x8000,0x4000,0x2000,0x2000,0x1000,0x0800,0x0400,0x0200,0x0100,0x0000,0x0000,0x0000,0x0000}; // 'ヽ' w=8
static const uint16_t KG_78[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x7c00,0x0200,0x0200,0x0200,0x0400,0x3800,0x0000,0x0000,0x0000,0x0000}; // 'っ' w=7
static const uint16_t KG_79[14] PROGMEM = {0x0000,0x0000,0x7e00,0x0100,0x0100,0x0100,0x0100,0x0200,0x0400,0x3800,0x0000,0x0000,0x0000,0x0000}; // 'つ' w=8
static const uint16_t KG_80[14] PROGMEM = {0x0000,0x0000,0x3e00,0x4000,0x8000,0x8000,0x8000,0x8000,0x4000,0x3e00,0x0000,0x0000,0x0000,0x0000}; // '⊂' w=7
static const uint16_t KG_81[14] PROGMEM = {0x0000,0x0000,0xf800,0x0400,0x0200,0x0200,0x0200,0x0200,0x0400,0xf800,0x0000,0x0000,0x0000,0x0000}; // '⊃' w=7
static const uint16_t KG_82[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xff00,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '─' w=8
static const uint16_t KG_83[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xff00,0xff00,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '━' w=8
static const uint16_t KG_84[14] PROGMEM = {0x0000,0x0000,0x1800,0x1800,0x1800,0x1800,0x1800,0xff00,0xff00,0x0000,0x0000,0x0000,0x0000,0x0000}; // '┻' w=8
static const uint16_t KG_85[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xff00,0x1000,0x1000,0x1000,0x1000,0x1000,0x1000,0x1000}; // '┬' w=8
static const uint16_t KG_86[14] PROGMEM = {0x0000,0x1000,0x1000,0x1000,0x1000,0x1000,0x1000,0xf000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '╯' w=8
static const uint16_t KG_87[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0x3c00,0x4200,0x8100,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '︵' w=8
static const uint16_t KG_88[14] PROGMEM = {0x9900,0x5a00,0xff00,0x0000,0x5400,0x5500,0xff00,0x9200,0x9200,0xff00,0x0000,0x0000,0x0000,0x0000}; // '益' w=8
static const uint16_t KG_89[14] PROGMEM = {0x0000,0x0000,0x0000,0x1000,0x2000,0x4000,0xff00,0x4000,0x2000,0x1000,0x0000,0x0000,0x0000,0x0000}; // '←' w=8
static const uint16_t KG_90[14] PROGMEM = {0x0000,0x0000,0x0000,0x0800,0x0400,0x0200,0xff00,0x0200,0x0400,0x0800,0x0000,0x0000,0x0000,0x0000}; // '→' w=8
static const uint16_t KG_91[14] PROGMEM = {0x0000,0x8000,0x6000,0x1800,0x6000,0x8000,0x0000,0xf800,0x0000,0xf800,0x0000,0x0000,0x0000,0x0000}; // '≧' w=5
static const uint16_t KG_92[14] PROGMEM = {0x0000,0x0800,0x3000,0xc000,0x3000,0x0800,0x0000,0xf800,0x0000,0xf800,0x0000,0x0000,0x0000,0x0000}; // '≦' w=5
static const uint16_t KG_93[14] PROGMEM = {0x3800,0x4000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x8000,0x4000,0x3800,0x0000,0x0000}; // 'ʕ' w=5
static const uint16_t KG_94[14] PROGMEM = {0xe000,0x1000,0x0800,0x0800,0x0800,0x0800,0x0800,0x0800,0x0800,0x0800,0x1000,0xe000,0x0000,0x0000}; // 'ʔ' w=5
static const uint16_t KG_95[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x4000,0x4000,0x4000,0x4800,0x9400,0x9400,0x6c00,0x0000,0x0000,0x0000}; // 'ʖ' w=6
static const uint16_t KG_96[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x8200,0xc600,0xba00,0x8200,0x4400,0x3800,0x0000,0x0000,0x0000,0x0000}; // 'ᴥ' w=7
static const uint16_t KG_97[14] PROGMEM = {0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x8400,0x7800,0x0000,0x0000}; // '͜' w=6
static const uint16_t KG_98[14] PROGMEM = {0x7800,0x8400,0x3000,0x3000,0x3000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000}; // '͡°' w=6
static const uint16_t KG_99[14] PROGMEM = {0x7c00,0x8200,0xba00,0xaa00,0xba00,0x8200,0x7c00,0x1000,0x2000,0x7c00,0x0000,0x0000,0x0000,0x0000}; // 'ಠ' w=7
static const uint16_t KG_100[14] PROGMEM = {0x7c00,0x8200,0xba00,0xaa00,0xaa00,0xb200,0x8600,0x7c00,0x1000,0x7c00,0x0000,0x0000,0x0000,0x0000}; // 'ಥ' w=7
static const uint16_t KG_101[14] PROGMEM = {0x0000,0x0000,0x0800,0x0800,0x1400,0x1400,0x2200,0x2200,0x4100,0x4100,0x8080,0x0000,0x0000,0x0000}; // '人' w=9
static const uint16_t KG_102[14] PROGMEM = {0x0000,0x0e00,0x3000,0x4e00,0x1000,0x2600,0x0800,0x1000,0x2000,0x4000,0x0000,0x0000,0x0000,0x0000}; // '彡' w=7
static const uint16_t* const KAOMOJI_GLYPH_ROWS[103] PROGMEM = {KG_0,KG_1,KG_2,KG_3,KG_4,KG_5,KG_6,KG_7,KG_8,KG_9,KG_10,KG_11,KG_12,KG_13,KG_14,KG_15,KG_16,KG_17,KG_18,KG_19,KG_20,KG_21,KG_22,KG_23,KG_24,KG_25,KG_26,KG_27,KG_28,KG_29,KG_30,KG_31,KG_32,KG_33,KG_34,KG_35,KG_36,KG_37,KG_38,KG_39,KG_40,KG_41,KG_42,KG_43,KG_44,KG_45,KG_46,KG_47,KG_48,KG_49,KG_50,KG_51,KG_52,KG_53,KG_54,KG_55,KG_56,KG_57,KG_58,KG_59,KG_60,KG_61,KG_62,KG_63,KG_64,KG_65,KG_66,KG_67,KG_68,KG_69,KG_70,KG_71,KG_72,KG_73,KG_74,KG_75,KG_76,KG_77,KG_78,KG_79,KG_80,KG_81,KG_82,KG_83,KG_84,KG_85,KG_86,KG_87,KG_88,KG_89,KG_90,KG_91,KG_92,KG_93,KG_94,KG_95,KG_96,KG_97,KG_98,KG_99,KG_100,KG_101,KG_102};
static const uint8_t KAOMOJI_GLYPH_W[] PROGMEM = {4,5,5,4,4,8,8,1,8,6,8,7,7,8,7,6,6,4,4,4,4,3,5,4,6,8,7,6,7,7,6,7,6,7,7,7,7,6,6,7,7,7,6,6,6,6,6,5,5,6,6,6,6,4,4,5,7,7,7,7,8,8,9,9,9,8,8,8,8,8,8,5,8,7,8,8,8,8,7,8,7,7,8,8,8,8,8,8,8,8,8,5,5,5,5,6,7,6,6,7,7,9,7};
static const char KAOMOJI_GLYPH_UTF8[] PROGMEM = "\xcd\xa1\xc2\xb0\x00\xe2\x8c\x90\x00\xe3\x83\xbb\x00\xe2\x80\xa2\x00\xe2\x97\x95\x00\xe2\x97\x8f\x00\xe2\x97\x8b\x00\xe2\x8a\x99\x00\xe2\x96\xa1\x00\xe2\x96\xa0\x00\xe2\x96\xbd\x00\xe2\x98\x86\x00\xe2\x98\x85\x00\xe2\x99\xa1\x00\xe2\x99\xa5\x00\xe2\x99\xaa\x00\xe2\x8c\x92\x00\xe2\x80\xbf\x00\xe3\x83\x84\x00\xe3\x83\xae\x00\xe3\x83\x8e\x00\xe3\x83\xbd\x00\xe3\x81\xa3\x00\xe3\x81\xa4\x00\xe2\x8a\x82\x00\xe2\x8a\x83\x00\xe2\x94\x80\x00\xe2\x94\x81\x00\xe2\x94\xbb\x00\xe2\x94\xac\x00\xe2\x95\xaf\x00\xef\xb8\xb5\x00\xe7\x9b\x8a\x00\xe2\x86\x90\x00\xe2\x86\x92\x00\xe2\x89\xa7\x00\xe2\x89\xa6\x00\xe1\xb4\xa5\x00\xe0\xb2\xa0\x00\xe0\xb2\xa5\x00\xe4\xba\xba\x00\xe5\xbd\xa1\x00\xc2\xb4\x00\xcb\x98\x00\xc2\xaf\x00\xc2\xac\x00\xc2\xb0\x00\xcf\x89\x00\xce\xb5\x00\xd0\x94\x00\xce\xa3\x00\xca\x95\x00\xca\x94\x00\xca\x96\x00\xcd\x9c\x00\x20\x00\x28\x00\x29\x00\x5b\x00\x5d\x00\x2f\x00\x5c\x00\x7c\x00\x5f\x00\x2d\x00\x7e\x00\x3d\x00\x2b\x00\x2a\x00\x5e\x00\x3c\x00\x3e\x00\x2e\x00\x2c\x00\x3b\x00\x3a\x00\x27\x00\x22\x00\x21\x00\x3f\x00\x23\x00\x40\x00\x6f\x00\x4f\x00\x30\x00\x78\x00\x58\x00\x75\x00\x55\x00\x76\x00\x56\x00\x54\x00\x63\x00\x7a\x00\x5a\x00\x57\x00\x77\x00\x6e\x00\x64\x00\x62\x00\x33\x00\x39\x00\x60\x00";
static const uint8_t KAOMOJI_GLYPH_KEYIDX[] PROGMEM = {98,52,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,96,99,100,101,102,47,49,50,51,53,70,71,72,73,93,94,95,97,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,48};

static const char KF_0[] PROGMEM = "\x28\x5e\x5f\x5e\x29"; // happy_classic: (^_^)
static const char KF_1[] PROGMEM = "\x28\x5e\x2d\x5e\x29"; // happy_dash: (^-^)
static const char KF_2[] PROGMEM = "\x28\x5e\x6f\x5e\x29"; // happy_open: (^o^)
static const char KF_3[] PROGMEM = "\x28\x5e\x2e\x5e\x29"; // happy_dot: (^.^)
static const char KF_4[] PROGMEM = "\x28\x5e\x76\x5e\x29"; // happy_vee: (^v^)
static const char KF_5[] PROGMEM = "\x5c\x28\x5e\x6f\x5e\x29\x2f"; // happy_cheer: \(^o^)/
static const char KF_6[] PROGMEM = "\x28\x6e\x5f\x6e\x29"; // happy_nn: (n_n)
static const char KF_7[] PROGMEM = "\x28\x5e\x5f\x5e\x29\x76"; // happy_peace: (^_^)v
static const char KF_8[] PROGMEM = "\x64\x28\x5e\x5f\x5e\x29\x62"; // happy_thumbs: d(^_^)b
static const char KF_9[] PROGMEM = "\x28\x2a\x5e\x5f\x5e\x2a\x29"; // happy_blush: (*^_^*)
static const char KF_10[] PROGMEM = "\x28\x5e\x5f\x7e\x29"; // happy_wink: (^_~)
static const char KF_11[] PROGMEM = "\x28\x7e\x5f\x5e\x29"; // happy_wink2: (~_^)
static const char KF_12[] PROGMEM = "\x28\xe2\x89\xa7\xe2\x96\xbd\xe2\x89\xa6\x29"; // happy_glee: (≧▽≦)
static const char KF_13[] PROGMEM = "\x5c\x28\xe2\x89\xa7\xe2\x96\xbd\xe2\x89\xa6\x29\x2f"; // happy_glee_cheer: \(≧▽≦)/
static const char KF_14[] PROGMEM = "\x28\xe2\x89\xa7\xcf\x89\xe2\x89\xa6\x29"; // happy_gleeful: (≧ω≦)
static const char KF_15[] PROGMEM = "\x28\xc2\xb4\xe2\x96\xbd\x60\x29"; // happy_soft: (´▽`)
static const char KF_16[] PROGMEM = "\x28\xc2\xb4\xcf\x89\x60\x29"; // happy_gentle: (´ω`)
static const char KF_17[] PROGMEM = "\x28\x6f\xc2\xb4\xe2\x96\xbd\x60\x6f\x29"; // happy_round: (o´▽`o)
static const char KF_18[] PROGMEM = "\xe3\x83\xbd\x28\xc2\xb4\xe2\x96\xbd\x60\x29\xe3\x83\x8e"; // happy_dance: ヽ(´▽`)ノ
static const char KF_19[] PROGMEM = "\xe3\x83\xbd\x28\x5e\x6f\x5e\x29\xe3\x83\x8e"; // happy_yay: ヽ(^o^)ノ
static const char KF_20[] PROGMEM = "\x28\xe2\x98\x86\xe2\x96\xbd\xe2\x98\x86\x29"; // happy_starstruck: (☆▽☆)
static const char KF_21[] PROGMEM = "\x28\xe2\x98\x85\xcf\x89\xe2\x98\x85\x29"; // happy_starry: (★ω★)
static const char KF_22[] PROGMEM = "\x28\xe2\x8c\x92\xe2\x80\xbf\xe2\x8c\x92\x29"; // happy_curve: (⌒‿⌒)
static const char KF_23[] PROGMEM = "\x28\xe2\x97\x95\xe2\x80\xbf\xe2\x97\x95\x29"; // happy_uwu: (◕‿◕)
static const char KF_24[] PROGMEM = "\x28\x27\xe2\x80\xbf\x27\x29"; // happy_dots: ('‿')
static const char KF_25[] PROGMEM = "\x28\x6f\xe2\x80\xbf\x6f\x29"; // happy_oo: (o‿o)
static const char KF_26[] PROGMEM = "\x28\x5e\xe2\x80\xbf\x5e\x29"; // happy_smilearc: (^‿^)
static const char KF_27[] PROGMEM = "\x28\x5e\x33\x5e\x29"; // happy_cheeky: (^3^)
static const char KF_28[] PROGMEM = "\xe2\x99\xaa\x28\xc2\xb4\xe2\x96\xbd\x60\x29"; // happy_note: ♪(´▽`)
static const char KF_29[] PROGMEM = "\x28\xe2\x97\x8f\xe2\x80\xbf\xe2\x97\x8f\x29"; // happy_bright: (●‿●)
static const char KF_30[] PROGMEM = "\x28\xe2\x99\xa1\x5f\xe2\x99\xa1\x29"; // love_hearteyes: (♡_♡)
static const char KF_31[] PROGMEM = "\x28\xe2\x99\xa5\x5f\xe2\x99\xa5\x29"; // love_hearteyes2: (♥_♥)
static const char KF_32[] PROGMEM = "\x28\xe2\x99\xa1\xcf\x89\xe2\x99\xa1\x29"; // love_soft: (♡ω♡)
static const char KF_33[] PROGMEM = "\x28\xe2\x99\xa1\xc2\xb4\xe2\x96\xbd\x60\xe2\x99\xa1\x29"; // love_glow: (♡´▽`♡)
static const char KF_34[] PROGMEM = "\xe2\x99\xa1\x28\xe2\x97\x95\xe2\x80\xbf\xe2\x97\x95\x29\xe2\x99\xa1"; // love_hug_heart: ♡(◕‿◕)♡
static const char KF_35[] PROGMEM = "\x28\xc2\xb4\xce\xb5\x60\x29\xe2\x99\xa1"; // love_kiss: (´ε`)♡
static const char KF_36[] PROGMEM = "\x28\xcb\x98\x33\xcb\x98\x29\xe2\x99\xa1"; // love_kiss2: (˘3˘)♡
static const char KF_37[] PROGMEM = "\x28\x2d\xce\xb5\x2d\x29\xe2\x99\xa1"; // love_kiss3: (-ε-)♡
static const char KF_38[] PROGMEM = "\x28\x2a\xe2\x99\xa1\xe2\x96\xbd\xe2\x99\xa1\x2a\x29"; // love_sparkle: (*♡▽♡*)
static const char KF_39[] PROGMEM = "\xe2\x99\xaa\x7e\x28\xc2\xb4\xce\xb5\x60\x29"; // love_whistle: ♪~(´ε`)
static const char KF_40[] PROGMEM = "\x28\x54\x5f\x54\x29"; // cry_classic: (T_T)
static const char KF_41[] PROGMEM = "\x28\x54\xe2\x96\xbd\x54\x29"; // cry_flood: (T▽T)
static const char KF_42[] PROGMEM = "\x28\x3b\x5f\x3b\x29"; // cry_semis: (;_;)
static const char KF_43[] PROGMEM = "\x28\x3b\xcf\x89\x3b\x29"; // cry_soft: (;ω;)
static const char KF_44[] PROGMEM = "\x28\xc2\xb4\x3b\xcf\x89\x3b\x60\x29"; // cry_stream: (´;ω;`)
static const char KF_45[] PROGMEM = "\x28\x54\x5e\x54\x29"; // cry_hard: (T^T)
static const char KF_46[] PROGMEM = "\x28\x54\x6f\x54\x29"; // cry_oh: (ToT)
static const char KF_47[] PROGMEM = "\x28\x54\xcf\x89\x54\x29"; // cry_wobble: (TωT)
static const char KF_48[] PROGMEM = "\x28\xe2\x94\xac\x5f\xe2\x94\xac\x29"; // cry_pillar: (┬_┬)
static const char KF_49[] PROGMEM = "\x28\xe0\xb2\xa5\x5f\xe0\xb2\xa5\x29"; // cry_stare: (ಥ_ಥ)
static const char KF_50[] PROGMEM = "\x28\x2e\x5f\x2e\x29"; // sad_blank: (._.)
static const char KF_51[] PROGMEM = "\x28\x2c\x5f\x2c\x29"; // sad_droop: (,_,)
static const char KF_52[] PROGMEM = "\x28\xc2\xb4\x5f\x60\x29"; // sad_quiet: (´_`)
static const char KF_53[] PROGMEM = "\x28\x75\x5f\x75\x29"; // sad_down: (u_u)
static const char KF_54[] PROGMEM = "\x28\x3d\x5f\x3d\x29"; // sad_sigh: (=_=)
static const char KF_55[] PROGMEM = "\x28\x3e\x5f\x3c\x29"; // sad_hurt: (>_<)
static const char KF_56[] PROGMEM = "\x28\xc2\xb0\x7e\xc2\xb0\x29"; // sad_worry: (°~°)
static const char KF_57[] PROGMEM = "\x28\x5e\x5f\x5e\x3b\x29"; // sad_sweat: (^_^;)
static const char KF_58[] PROGMEM = "\x28\x2e\x5f\x2e\x3b\x29"; // sad_nervous: (._.;)
static const char KF_59[] PROGMEM = "\x28\xc2\xb4\x7e\x60\x29"; // sad_strain: (´~`)
static const char KF_60[] PROGMEM = "\x28\x3e\x7e\x3c\x29"; // sad_wince: (>~<)
static const char KF_61[] PROGMEM = "\x28\xe0\xb2\xa0\x5f\xe0\xb2\xa0\x29"; // angry_look: (ಠ_ಠ)
static const char KF_62[] PROGMEM = "\x28\xe0\xb2\xa0\xe7\x9b\x8a\xe0\xb2\xa0\x29"; // angry_rage_look: (ಠ益ಠ)
static const char KF_63[] PROGMEM = "\x28\xc2\xac\x5f\xc2\xac\x29"; // angry_side: (¬_¬)
static const char KF_64[] PROGMEM = "\x28\x60\xd0\x94\xc2\xb4\x29"; // angry_growl: (`Д´)
static const char KF_65[] PROGMEM = "\x28\x23\x60\xd0\x94\xc2\xb4\x29"; // angry_vein: (#`Д´)
static const char KF_66[] PROGMEM = "\x28\x60\xcf\x89\xc2\xb4\x29"; // angry_grr: (`ω´)
static const char KF_67[] PROGMEM = "\x28\x60\x5f\xc2\xb4\x29"; // angry_plain: (`_´)
static const char KF_68[] PROGMEM = "\x28\xc2\xb0\xe7\x9b\x8a\xc2\xb0\x29"; // angry_boil: (°益°)
static const char KF_69[] PROGMEM = "\x28\xe3\x83\x8e\x60\xd0\x94\xc2\xb4\x29\xe3\x83\x8e"; // angry_charge: (ノ`Д´)ノ
static const char KF_70[] PROGMEM = "\x28\xe2\x95\xaf\xc2\xb0\xe2\x96\xa1\xc2\xb0\x29\xe2\x95\xaf\xef\xb8\xb5\x20\xe2\x94\xbb\xe2\x94\x81\xe2\x94\xbb"; // angry_tableflip: (╯°□°)╯︵ ┻━┻
static const char KF_71[] PROGMEM = "\xe2\x94\xac\xe2\x94\x80\xe2\x94\xac\xe3\x83\x8e\x28\xc2\xb0\x5f\xc2\xb0\xe3\x83\x8e\x29"; // angry_tableback: ┬─┬ノ(°_°ノ)
static const char KF_72[] PROGMEM = "\x28\xe2\x80\xa2\x60\x5f\xc2\xb4\xe2\x80\xa2\x29"; // angry_glare: (•`_´•)
static const char KF_73[] PROGMEM = "\x28\x4f\x5f\x4f\x29"; // surp_big: (O_O)
static const char KF_74[] PROGMEM = "\x28\x6f\x5f\x6f\x29"; // surp_small: (o_o)
static const char KF_75[] PROGMEM = "\x28\x30\x5f\x30\x29"; // surp_zero: (0_0)
static const char KF_76[] PROGMEM = "\x28\x4f\x2e\x4f\x29"; // surp_dot: (O.O)
static const char KF_77[] PROGMEM = "\x28\xc2\xb0\x6f\xc2\xb0\x29"; // surp_deg: (°o°)
static const char KF_78[] PROGMEM = "\x28\xc2\xb0\x4f\xc2\xb0\x29"; // surp_deg2: (°O°)
static const char KF_79[] PROGMEM = "\x28\xc2\xb0\xe2\x96\xa1\xc2\xb0\x29"; // surp_shock: (°□°)
static const char KF_80[] PROGMEM = "\x77\x28\xc2\xb0\x6f\xc2\xb0\x29\x77"; // surp_wow: w(°o°)w
static const char KF_81[] PROGMEM = "\xce\xa3\x28\xc2\xb0\xe2\x96\xa1\xc2\xb0\x29"; // surp_jump: Σ(°□°)
static const char KF_82[] PROGMEM = "\xce\xa3\x28\x4f\x5f\x4f\x29"; // surp_jolt: Σ(O_O)
static const char KF_83[] PROGMEM = "\x28\x40\x5f\x40\x29"; // surp_dizzy: (@_@)
static const char KF_84[] PROGMEM = "\x28\xe2\x8a\x99\x5f\xe2\x8a\x99\x29"; // surp_target: (⊙_⊙)
static const char KF_85[] PROGMEM = "\x28\x3f\x5f\x3f\x29"; // conf_what: (?_?)
static const char KF_86[] PROGMEM = "\x28\x6f\x5f\x4f\x29"; // conf_skew: (o_O)
static const char KF_87[] PROGMEM = "\x28\x4f\x5f\x6f\x29"; // conf_skew2: (O_o)
static const char KF_88[] PROGMEM = "\x28\xe3\x83\xbb\x5f\xe3\x83\xbb\x29"; // conf_dot: (・_・)
static const char KF_89[] PROGMEM = "\x28\xe3\x83\xbb\xcf\x89\xe3\x83\xbb\x29"; // conf_soft: (・ω・)
static const char KF_90[] PROGMEM = "\x28\xe2\x86\x92\x5f\xe2\x86\x92\x29"; // conf_shifty_r: (→_→)
static const char KF_91[] PROGMEM = "\x28\xe2\x86\x90\x5f\xe2\x86\x90\x29"; // conf_shifty_l: (←_←)
static const char KF_92[] PROGMEM = "\x28\x7e\x5f\x7e\x29"; // conf_hmm: (~_~)
static const char KF_93[] PROGMEM = "\x28\x2d\x5f\x2d\x29"; // sleep_flat: (-_-)
static const char KF_94[] PROGMEM = "\x28\x3d\x5f\x3d\x29\x7a\x7a\x7a"; // sleep_heavy: (=_=)zzz
static const char KF_95[] PROGMEM = "\x28\x2d\x2e\x2d\x29"; // sleep_dot: (-.-)
static const char KF_96[] PROGMEM = "\x28\x2d\xcf\x89\x2d\x29"; // sleep_soft: (-ω-)
static const char KF_97[] PROGMEM = "\x28\xcb\x98\xcf\x89\xcb\x98\x29"; // sleep_cozy: (˘ω˘)
static const char KF_98[] PROGMEM = "\x28\x2d\x5f\x2d\x29\x7a\x7a\x7a"; // sleep_zz: (-_-)zzz
static const char KF_99[] PROGMEM = "\x28\x3d\xcf\x89\x3d\x29"; // sleep_calm: (=ω=)
static const char KF_100[] PROGMEM = "\x28\x20\xcd\xa1\xc2\xb0\x20\xcd\x9c\xca\x96\x20\xcd\xa1\xc2\xb0\x29"; // cool_lenny: ( ͡° ͜ʖ ͡°)
static const char KF_101[] PROGMEM = "\x28\xc2\xac\xe2\x80\xbf\xc2\xac\x29"; // cool_smug: (¬‿¬)
static const char KF_102[] PROGMEM = "\x28\xe2\x96\xa0\x5f\xe2\x96\xa0\x29"; // cool_shades: (■_■)
static const char KF_103[] PROGMEM = "\x28\xe2\x8c\x90\xe2\x96\xa0\x5f\xe2\x96\xa0\x29"; // cool_dealwith: (⌐■_■)
static const char KF_104[] PROGMEM = "\x5b\xe2\x96\xa0\x5f\xe2\x96\xa0\x5d"; // cool_robot: [■_■]
static const char KF_105[] PROGMEM = "\xc2\xaf\x5c\x5f\x28\xe3\x83\x84\x29\x5f\x2f\xc2\xaf"; // act_shrug: ¯\_(ツ)_/¯
static const char KF_106[] PROGMEM = "\xe3\x83\xbd\x28\xe3\x83\x84\x29\xe3\x83\x8e"; // act_shrug_dance: ヽ(ツ)ノ
static const char KF_107[] PROGMEM = "\x28\xe3\x81\xa3\xc2\xb4\xe2\x96\xbd\x60\x29\xe3\x81\xa3"; // act_hug: (っ´▽`)っ
static const char KF_108[] PROGMEM = "\x28\xe2\x8a\x83\xc2\xb4\xe2\x96\xbd\x60\x29\xe2\x8a\x83"; // act_hug_big: (⊃´▽`)⊃
static const char KF_109[] PROGMEM = "\x28\xe3\x81\xa4\xc2\xb0\xcf\x89\xc2\xb0\x29\xe3\x81\xa4"; // act_hug_want: (つ°ω°)つ
static const char KF_110[] PROGMEM = "\x28\xe3\x83\x8e\xc2\xb4\xe2\x96\xbd\x60\x29\xe3\x83\x8e"; // act_celebrate: (ノ´▽`)ノ
static const char KF_111[] PROGMEM = "\xe3\x83\xbd\x28\xc2\xb0\xe2\x96\xa1\xc2\xb0\x29\xe3\x83\x8e"; // act_panic: ヽ(°□°)ノ
static const char KF_112[] PROGMEM = "\xce\xb5\x3d\xce\xb5\x3d\x28\xe3\x83\x8e\xe2\x89\xa7\xe2\x96\xbd\xe2\x89\xa6\x29\xe3\x83\x8e"; // act_run: ε=ε=(ノ≧▽≦)ノ
static const char KF_113[] PROGMEM = "\x28\x6f\xc2\xb0\xcf\x89\xc2\xb0\x29\x6f"; // act_fight: (o°ω°)o
static const char KF_114[] PROGMEM = "\x28\x5e\x5f\x5e\x29\x2f"; // act_wave: (^_^)/
static const char KF_115[] PROGMEM = "\x28\xc2\xb4\xe2\x96\xbd\x60\x29\x2f"; // act_wave_soft: (´▽`)/
static const char KF_116[] PROGMEM = "\xe3\x83\xbd\x28\x5e\x5f\x5e\x29"; // act_hello: ヽ(^_^)
static const char KF_117[] PROGMEM = "\x28\xe3\x83\x8e\xe2\x97\x95\xe3\x83\xae\xe2\x97\x95\x29\xe3\x83\x8e\x2a\x3a\xe3\x83\xbb"; // act_magic: (ノ◕ヮ◕)ノ*:・
static const char KF_118[] PROGMEM = "\xe3\x83\xbd\x28\x5e\xe2\x96\xbd\x5e\x29\xe3\x83\x8e"; // act_party: ヽ(^▽^)ノ
static const char KF_119[] PROGMEM = "\xe2\x98\x86\xe5\xbd\xa1"; // act_star: ☆彡
static const char KF_120[] PROGMEM = "\xca\x95\xe2\x80\xa2\xe1\xb4\xa5\xe2\x80\xa2\xca\x94"; // bear: ʕ•ᴥ•ʔ
static const char KF_121[] PROGMEM = "\xca\x95\xc2\xb4\xe2\x80\xa2\xe1\xb4\xa5\xe2\x80\xa2\x60\xca\x94"; // bear_happy: ʕ´•ᴥ•`ʔ
static const char KF_122[] PROGMEM = "\x28\x3d\x5e\xe3\x83\xbb\x5e\x3d\x29"; // cat: (=^・^=)
static const char KF_123[] PROGMEM = "\x28\x3d\x5e\xcf\x89\x5e\x3d\x29"; // cat_soft: (=^ω^=)
static const char KF_124[] PROGMEM = "\x28\x3d\x60\xcf\x89\xc2\xb4\x3d\x29"; // cat_grump: (=`ω´=)
static const char KF_125[] PROGMEM = "\x28\x55\xe3\x83\xbb\xe1\xb4\xa5\xe3\x83\xbb\x55\x29"; // dog: (U・ᴥ・U)
static const char KF_126[] PROGMEM = "\x3c\xc2\xb0\x29\x29\x29\x29\x3e\x3c"; // fish: <°))))><
static const char KF_127[] PROGMEM = "\x5b\x6f\x5f\x6f\x5d"; // robot_neutral: [o_o]
static const char KF_128[] PROGMEM = "\x5b\x5e\x5f\x5e\x5d"; // robot_happy: [^_^]
static const char KF_129[] PROGMEM = "\x5b\xc2\xb0\x5f\xc2\xb0\x5d"; // robot_deg: [°_°]
static const char KF_130[] PROGMEM = "\x5b\x2d\x5f\x2d\x5d"; // robot_sleep: [-_-]
static const char KF_131[] PROGMEM = "\x5b\xe2\x99\xa1\x5f\xe2\x99\xa1\x5d"; // robot_love: [♡_♡]
static const char KF_132[] PROGMEM = "\x5b\xc2\xb0\xe2\x96\xa1\xc2\xb0\x5d"; // robot_shock: [°□°]
static const char KF_133[] PROGMEM = "\x28\x78\x5f\x78\x29"; // dead_x: (x_x)
static const char KF_134[] PROGMEM = "\x28\x58\x5f\x58\x29"; // dead_XX: (X_X)
static const char KF_135[] PROGMEM = "\x28\x2b\x5f\x2b\x29"; // dead_plus: (+_+)
static const char KF_136[] PROGMEM = "\x28\xe2\x89\xa7\xe2\x96\xbd\xe2\x89\xa6\x29"; // happy_grin: (≧▽≦)
static const char KF_137[] PROGMEM = "\x28\x4f\xe2\x96\xbd\x4f\x29"; // happy_beam: (O▽O)
static const char KF_138[] PROGMEM = "\x28\x3e\xe2\x96\xbd\x3c\x29"; // happy_squee: (>▽<)
static const char KF_139[] PROGMEM = "\x28\x3b\xe2\x96\xbd\x3b\x29"; // happy_tearsjoy: (;▽;)
static const char KF_140[] PROGMEM = "\x28\xc2\xb4\xe2\x80\xbf\x60\x29"; // happy_flower: (´‿`)
static const char KF_141[] PROGMEM = "\x28\x6f\xe2\x80\xbf\x4f\x29"; // happy_ooo: (o‿O)
static const char KF_142[] PROGMEM = "\x5c\x28\xc2\xb4\xe2\x96\xbd\x60\x29\x2f"; // happy_hooray: \(´▽`)/
static const char KF_143[] PROGMEM = "\xe3\x83\xbd\x28\xe2\x89\xa7\xcf\x89\xe2\x89\xa6\x29\xe3\x83\x8e"; // happy_bounce: ヽ(≧ω≦)ノ
static const char KF_144[] PROGMEM = "\x28\xe2\x98\x86\xe2\x80\xbf\xe2\x98\x86\x29"; // happy_twinkle: (☆‿☆)
static const char KF_145[] PROGMEM = "\x28\x5e\xe2\x96\xbd\x5e\x29"; // happy_proud: (^▽^)
static const char KF_146[] PROGMEM = "\x28\xe2\x8c\x92\xe2\x96\xbd\xe2\x8c\x92\x29"; // happy_wide: (⌒▽⌒)
static const char KF_147[] PROGMEM = "\x28\xcb\x98\xe2\x80\xbf\xcb\x98\x29"; // happy_warm: (˘‿˘)
static const char KF_148[] PROGMEM = "\x28\x2f\xe2\x99\xa1\x5f\xe2\x99\xa1\x29\x2f"; // love_shy: (/♡_♡)/
static const char KF_149[] PROGMEM = "\x28\xe2\x99\xa5\xe2\x80\xbf\xe2\x99\xa5\x29"; // love_beam: (♥‿♥)
static const char KF_150[] PROGMEM = "\x28\xe3\x83\x8e\xe2\x99\xa1\xe2\x96\xbd\xe2\x99\xa1\x29\xe3\x83\x8e"; // love_throw: (ノ♡▽♡)ノ
static const char KF_151[] PROGMEM = "\x28\xc2\xb4\xe2\x99\xa1\xe2\x80\xbf\xe2\x99\xa1\x60\x29"; // love_daydream: (´♡‿♡`)
static const char KF_152[] PROGMEM = "\x28\x3d\xe2\x99\xa1\xcf\x89\xe2\x99\xa1\x3d\x29"; // love_cat: (=♡ω♡=)
static const char KF_153[] PROGMEM = "\x28\xc2\xb4\x2d\x5f\x2d\x60\x29"; // sad_gloom: (´-_-`)
static const char KF_154[] PROGMEM = "\x28\x3b\x4f\x3b\x29"; // sad_rain: (;O;)
static const char KF_155[] PROGMEM = "\x28\x3b\xe4\xba\xba\x3b\x29"; // sad_please: (;人;)
static const char KF_156[] PROGMEM = "\x28\x3d\xd0\x94\x3d\x29"; // sad_tired: (=Д=)
static const char KF_157[] PROGMEM = "\x28\xc2\xb4\xd0\x94\x60\x29"; // sad_defeat: (´Д`)
static const char KF_158[] PROGMEM = "\x28\xc2\xac\xe7\x9b\x8a\xc2\xac\x29"; // angry_fume: (¬益¬)
static const char KF_159[] PROGMEM = "\x28\x3e\xd0\x94\x3c\x29"; // angry_snap: (>Д<)
static const char KF_160[] PROGMEM = "\x28\x60\xe2\x97\x95\xe2\x80\xbf\xe2\x97\x95\xc2\xb4\x29"; // angry_scheme: (`◕‿◕´)
static const char KF_161[] PROGMEM = "\x28\xe2\x8a\x99\xd0\x94\xe2\x8a\x99\x29"; // surp_gasp: (⊙Д⊙)
static const char KF_162[] PROGMEM = "\x28\xe2\x97\x8f\x5f\xe2\x97\x8f\x29"; // surp_blink: (●_●)
static const char KF_163[] PROGMEM = "\x28\x4f\x5f\x4f\x29"; // surp_frozen: (O_O)
static const char KF_164[] PROGMEM = "\x28\x40\xcf\x89\x40\x29"; // conf_swirl: (@ω@)
static const char KF_165[] PROGMEM = "\x28\xc2\xb0\xcf\x89\xc2\xb0\x3b\x29"; // conf_broken: (°ω°;)
static const char KF_166[] PROGMEM = "\x28\xe3\x83\xbb\x5f\xe3\x83\xbb\x3f\x29"; // conf_tilt: (・_・?)
static const char KF_167[] PROGMEM = "\x28\x2d\xe4\xba\xba\x2d\x29"; // act_pray: (-人-)
static const char KF_168[] PROGMEM = "\x28\xc2\xb4\xe4\xba\xba\x60\x29"; // act_please: (´人`)
static const char KF_169[] PROGMEM = "\x28\xe3\x83\x8e\xc2\xb0\xe2\x96\xbd\xc2\xb0\x29\xe3\x83\x8e\xe2\x98\x86\xe5\xbd\xa1"; // act_throw_star: (ノ°▽°)ノ☆彡
static const char KF_170[] PROGMEM = "\x28\xe2\x8a\x83\xc2\xb0\xe2\x96\xbd\xc2\xb0\x29\xe2\x8a\x83"; // act_catch: (⊃°▽°)⊃
static const char KF_171[] PROGMEM = "\xce\xb5\x3d\x28\xe3\x83\x8e\xe3\x83\xbb\xcf\x89\xe3\x83\xbb\x29\xe3\x83\x8e"; // act_march: ε=(ノ・ω・)ノ
static const char KF_172[] PROGMEM = "\x5c\x28\xe2\x98\x86\xe2\x96\xbd\xe2\x98\x86\x29\x2f"; // act_tada: \(☆▽☆)/
static const char KF_173[] PROGMEM = "\x28\xe3\x81\xa3\xc2\xb4\xcf\x89\x60\x29\xe3\x81\xa3"; // act_comfort: (っ´ω`)っ
static const char KF_174[] PROGMEM = "\x28\x5e\x5f\x5e\x29\xe4\xba\xba\x28\x5e\x5f\x5e\x29"; // act_highfive: (^_^)人(^_^)
static const char KF_175[] PROGMEM = "\xe3\x83\xbd\x28\xc2\xb4\xe2\x96\xbd\x60\x29\xe3\x83\x8e"; // act_cheer_pair: ヽ(´▽`)ノ
static const char KF_176[] PROGMEM = "\x28\x5e\x5f\x5e\x29\x2f"; // act_salute: (^_^)/
static const char KF_177[] PROGMEM = "\xca\x95\xe2\x80\xa2\xe1\xb4\xa5\xe2\x80\xa2\xca\x94\xe3\x83\x8e"; // bear_wave: ʕ•ᴥ•ʔノ
static const char KF_178[] PROGMEM = "\xca\x95\xe2\x99\xa1\xe1\xb4\xa5\xe2\x99\xa1\xca\x94"; // bear_love: ʕ♡ᴥ♡ʔ
static const char KF_179[] PROGMEM = "\x28\x3d\x2d\xcf\x89\x2d\x3d\x29"; // cat_sleep: (=-ω-=)
static const char KF_180[] PROGMEM = "\x28\x3d\xc2\xb0\xcf\x89\xc2\xb0\x3d\x29"; // cat_alert: (=°ω°=)
static const char KF_181[] PROGMEM = "\x28\x55\x5e\xe1\xb4\xa5\x5e\x55\x29"; // dog_happy: (U^ᴥ^U)
static const char KF_182[] PROGMEM = "\x28\xe3\x83\xbb\xe2\x97\x95\xe3\x83\xbb\x29"; // bird_look: (・◕・)
static const char KF_183[] PROGMEM = "\x5b\x5e\x5f\x7e\x5d"; // robot_wink: [^_~]
static const char KF_184[] PROGMEM = "\x5b\xe2\x89\xa7\xe2\x96\xbd\xe2\x89\xa6\x5d"; // robot_glee: [≧▽≦]
static const char KF_185[] PROGMEM = "\x5b\xc2\xac\x5f\xc2\xac\x5d"; // robot_hmm: [¬_¬]
static const char KF_186[] PROGMEM = "\x5b\xe2\x97\x95\xe2\x80\xbf\xe2\x97\x95\x5d"; // robot_uwu: [◕‿◕]
static const char KF_187[] PROGMEM = "\x5b\x78\x5f\x78\x5d"; // robot_dead: [x_x]
static const char KF_188[] PROGMEM = "\x5b\xe2\x98\x86\x5f\xe2\x98\x86\x5d"; // robot_star: [☆_☆]
static const char KF_189[] PROGMEM = "\x5b\x6f\x5f\x6f\x5d\x2f"; // robot_wave: [o_o]/
static const char KF_190[] PROGMEM = "\x5b\x2d\xe4\xba\xba\x2d\x5d"; // robot_zen: [-人-]
static const char* const KAOMOJI_FACES[191] PROGMEM = {KF_0,KF_1,KF_2,KF_3,KF_4,KF_5,KF_6,KF_7,KF_8,KF_9,KF_10,KF_11,KF_12,KF_13,KF_14,KF_15,KF_16,KF_17,KF_18,KF_19,KF_20,KF_21,KF_22,KF_23,KF_24,KF_25,KF_26,KF_27,KF_28,KF_29,KF_30,KF_31,KF_32,KF_33,KF_34,KF_35,KF_36,KF_37,KF_38,KF_39,KF_40,KF_41,KF_42,KF_43,KF_44,KF_45,KF_46,KF_47,KF_48,KF_49,KF_50,KF_51,KF_52,KF_53,KF_54,KF_55,KF_56,KF_57,KF_58,KF_59,KF_60,KF_61,KF_62,KF_63,KF_64,KF_65,KF_66,KF_67,KF_68,KF_69,KF_70,KF_71,KF_72,KF_73,KF_74,KF_75,KF_76,KF_77,KF_78,KF_79,KF_80,KF_81,KF_82,KF_83,KF_84,KF_85,KF_86,KF_87,KF_88,KF_89,KF_90,KF_91,KF_92,KF_93,KF_94,KF_95,KF_96,KF_97,KF_98,KF_99,KF_100,KF_101,KF_102,KF_103,KF_104,KF_105,KF_106,KF_107,KF_108,KF_109,KF_110,KF_111,KF_112,KF_113,KF_114,KF_115,KF_116,KF_117,KF_118,KF_119,KF_120,KF_121,KF_122,KF_123,KF_124,KF_125,KF_126,KF_127,KF_128,KF_129,KF_130,KF_131,KF_132,KF_133,KF_134,KF_135,KF_136,KF_137,KF_138,KF_139,KF_140,KF_141,KF_142,KF_143,KF_144,KF_145,KF_146,KF_147,KF_148,KF_149,KF_150,KF_151,KF_152,KF_153,KF_154,KF_155,KF_156,KF_157,KF_158,KF_159,KF_160,KF_161,KF_162,KF_163,KF_164,KF_165,KF_166,KF_167,KF_168,KF_169,KF_170,KF_171,KF_172,KF_173,KF_174,KF_175,KF_176,KF_177,KF_178,KF_179,KF_180,KF_181,KF_182,KF_183,KF_184,KF_185,KF_186,KF_187,KF_188,KF_189,KF_190};
static const char* const KAOMOJI_CATEGORY_NAMES[] PROGMEM = {"action","angry","animal","confused","cool","dead","happy","love","robot","sad","sleepy","surprised"};
#define KAOMOJI_CATEGORY_COUNT 12
static const uint8_t KAOMOJI_FACE_CATEGORY[] PROGMEM = {6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,7,7,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,1,1,1,1,1,1,1,1,1,1,1,1,11,11,11,11,11,11,11,11,11,11,11,11,3,3,3,3,3,3,3,3,10,10,10,10,10,10,10,4,4,4,4,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,8,8,8,8,8,8,5,5,5,6,6,6,6,6,6,6,6,6,6,6,6,7,7,7,7,7,9,9,9,9,9,1,1,1,11,11,11,3,3,3,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,8,8,8,8,8,8,8,8};


// ---- tokenizer: longest-match against the glyph table -----------------
static inline int kaomoji_match_(const char* s, uint8_t* gid) {
  const char* p = KAOMOJI_GLYPH_UTF8;
  for (uint16_t k = 0; k < KAOMOJI_GLYPHS; k++) {
    uint8_t n = 0;
    while (pgm_read_byte(p + n)) n++;
    uint8_t ok = 1;
    for (uint8_t j = 0; j < n; j++)
      if ((uint8_t)s[j] != pgm_read_byte(p + j)) { ok = 0; break; }
    if (ok && n) { *gid = pgm_read_byte(&KAOMOJI_GLYPH_KEYIDX[k]); return n; }
    p += n + 1;
  }
  return 0;   // unknown byte - caller skips one byte
}

// pixel width of a face when rendered (0 if any glyph is unknown)
static inline int kaomoji_width(const char* face) {
  int w = 0, first = 1;
  while (*face) {
    uint8_t gid; int n = kaomoji_match_(face, &gid);
    if (!n) { face++; continue; }
    if (!first) w += 1;
    w += pgm_read_byte(&KAOMOJI_GLYPH_W[gid]);
    first = 0; face += n;
  }
  return w;
}

// Render a face centred into a 1024-byte SSD1306 page buffer (128x64,
// 8 pages, LSB = top row of page) - identical to a GDA1 animation frame.
// Clears the buffer first. Returns rendered width in px.
static inline int kaomoji_render(const char* face, uint8_t* frame1024) {
  memset(frame1024, 0, 1024);
  int total = kaomoji_width(face);
  int x = (128 - total) / 2;
  if (x < 0) x = 0;
  while (*face) {
    uint8_t gid; int n = kaomoji_match_(face, &gid);
    if (!n) { face++; continue; }
    const uint16_t* rows = (const uint16_t*)pgm_read_ptr(&KAOMOJI_GLYPH_ROWS[gid]);
    uint8_t gw = pgm_read_byte(&KAOMOJI_GLYPH_W[gid]);
    for (uint8_t ry = 0; ry < KAOMOJI_CELL_H; ry++) {
      uint16_t bits = pgm_read_word(&rows[ry]);
      uint8_t y = KAOMOJI_TOP + ry;
      for (uint8_t rx = 0; rx < gw; rx++) {
        if (bits & (0x8000 >> rx)) {
          int px = x + rx;
          if (px >= 0 && px < 128)
            frame1024[(y >> 3) * 128 + px] |= (1 << (y & 7));
        }
      }
    }
    x += gw + 1; face += n;
  }
  return total;
}

// convenience accessors (face strings live in PROGMEM)
static inline const char* kaomoji_face(uint16_t i) {
  return (const char*)pgm_read_ptr(&KAOMOJI_FACES[i]);
}
static inline uint8_t kaomoji_category(uint16_t i) {
  return pgm_read_byte(&KAOMOJI_FACE_CATEGORY[i]);
}
// render face #i straight into a frame buffer
static inline int kaomoji_show(uint16_t i, uint8_t* frame1024) {
  char buf[48];
  const char* f = kaomoji_face(i % KAOMOJI_COUNT);
  uint8_t j = 0;
  while (j < sizeof(buf) - 1 && (buf[j] = pgm_read_byte(f + j))) j++;
  buf[j] = 0;
  return kaomoji_render(buf, frame1024);
}

